analyzer:
  errors:
    inference_failure_on_function_invocation: ignore
    inference_failure_on_generic_invocation: ignore
    inference_failure_on_instance_creation: ignore
    library_private_types_in_public_api: ignore
    lines_longer_than_80_chars: ignore
    parameter_assignments: ignore
    public_member_api_docs: ignore    
    sort_child_properties_last: ignore
    unnecessary_await_in_return: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

include: package:very_good_analysis/analysis_options.yaml
