// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj4dF7XvrmQyef6Dex_GfgNKfoQPcgrC8',
    appId: '1:468237529510:android:9cdd52a155698c53bc5f67',
    messagingSenderId: '468237529510',
    projectId: 'fir-login-27a05',
    storageBucket: 'fir-login-27a05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiEhiRcd3rJ-fcI99hdk2JBqW5FNiWM9w',
    appId: '1:468237529510:ios:cdec0c0306c7de7abc5f67',
    messagingSenderId: '468237529510',
    projectId: 'fir-login-27a05',
    storageBucket: 'fir-login-27a05.appspot.com',
    androidClientId: '468237529510-8c3qeudgukdiujrs6m5cgq3d3fte44pj.apps.googleusercontent.com',
    iosClientId: '468237529510-54ldimdelitkea87bfr6rus2b8pfubrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

}